### PR TITLE
Add missing build dependency.

### PR DESCRIPTION
**Pull request by puck**

### CODE REVIEW

**Comment by gibus** [comment]
Actually `Test::NoWarnings` is already included by `RT::Test` which is the base class for `RT::Extension::REST2::Test`.

**Comment by puck** [comment]
Interesting, as I found I had to explicitly install that package for tests to work.

**Comment by puck** [comment]
I had to add this dependency as the Debian packaging for request-tracker4 quite rightly doesn't depend on the packages required for running unit tests.

**Comment by sunnavy** [comment]
It looks more like the debian's package issue.

Anyway, as we are going to core REST2, this won't be an issue soon.

**Comment by puck** [comment]
Ah, it is a Build Depends on the request-tracker4 package. I'm happy to close this, and great to hear that this API will be going into core!

**Pull request closed without merging**
