### PR TITLE
Delete single ocfv

### PR DESCRIPTION
**Pull request by gibus**
This pull request is an addition to PR #25 allowing to delete a single OCFV. Here's the doc:

To delete a single-value custom field, set its value to JSON null (undef
in Perl):

        "CustomFields": {
            "XX_SINGLE_CF_ID_XX" : null
        }

### CODE REVIEW

**Comment by puck** [comment]
Hey @gibus,

I'm just trying out this patch set, and I'm getting the following error from the test suite:

Not a SCALAR reference at /usr/share/perl5/HTTP/Message.pm line 163.

This is the test where you create a ticket with a multipart form supplying a binary CustomField value.

Any suggestions?

I've also cherry picked 69e734517928db5b992b610b074a7f44d559b44a .

Cheers,
Andrew

**Comment by gibus** [comment]
Humm nope sorry, I haven't touched to REST2 extension for a while, never seen this error IIRC

**Comment by puck** [comment]
I've tracked the issue down. I'm testing on a Debian Jessie machine (ancient I know), because that's what my prod server is. The version of HTTP::Message in Debian Jessie is 6.06, version 6.07 introduced support for PUT to receive content data via hash refs - which is what the new tests in t/ticket-customfields.t uses.

**Comment by sunnavy** [comment]
Merged and thanks!

**Pull request closed without merging**
