### PR TITLE
Use showuserhistory acl

### PR DESCRIPTION
**Pull request by elacour**
REST2 up to now doesn't allow any user to see other users properties, even there is "ShowUserHistory" granted at global level. This PR allow this. I expect that RT API stil check for any unalllowed access/modifications later.

### CODE REVIEW

**Comment by sunnavy** [comment]
As privileged users could get other users info via web UI, we refactored related code accordingly, which includes rights check like ShowUserHistory.

Thanks!

**Comment by elacour** [comment]
Just discovered that your version request that user doing the API search is privileged. Why? It's allowed to give unprivileged users ShowUserHistory right and it should work through the API too.

**Comment by sunnavy** [comment]
Hi elacour

This is mainly to mirror the behavior of web UI: unprivileged couldn't access other users info there, even with ShowUserHistory.

On the other hand, ShowUserHistory is to allow to get user's change history, to me it's not the proper right to search users or get users info.

Thanks!
sunnavy

**Comment by sunnavy** [comment]
There is a config [AllowUserAutocompleteForUnprivileged](https://docs.bestpractical.com/rt/5.0.0/RT_Config.html#AllowUserAutocompleteForUnprivileged), as autocomplete implies search, I think we can probably use this instead to allow unprivileged users to search users or get user info.

**Pull request closed without merging**
