### PR TITLE
Create ticket with attachments multipart

### PR DESCRIPTION
**Pull request by gibus**
This pull request is an addition to PR #17 allowing to specify attachments for ticket creation with a multipart/form-data POST request. Here's the doc:

    Encoding the content of attachments file in MIME Base64 has the drawback
    of adding some processing overhead and to increase the sent data size by
    around 33%. RT's REST2 API provides another way to attach any binary or
    text file to your ticket by POSTing, instead of a JSON request, a
    multipart/form-data request. This kind of request is similar to what the
    browser sends when you add attachments in RT's ticket creation form. As
    its name suggests, a multipart/form-data request message contains a
    series of parts, each representing a form field. To create a ticket with
    attachments, the request has to include a field named Json, which, as
    previously, is a JSON object with Queue, Subject, Content, ContentType,
    etc. properties. Files can then be attached by specifying a field named
    Attachment for each of them, with the content of the file as value and
    the appropriate MIME type.

    The curl invocation is quite straith forward:

        curl -X POST
             -H "Content-Type: multipart/form-data"
             -F 'Json={
                        "Queue"      : "General",
                        "Subject"    : "hello world",
                        "Content"    : "That <em>damned</em> printer is out of order <b>again</b>!",
                        "ContentType": "text/html",
                        "TimeTaken"  : "1"
                      };type=application/json'
             -F 'Attachment=@/tmp/image.png;type=image/png'
             -F 'Attachment=@/etc/cups/cupsd.conf;type=text/plain'
             -H 'Authorization: token XX_TOKEN_XX'
                'XX_TICKET_URL_XX'/comment

    As a sidenote, fields for attached files can also be named attachment_1,
    attachment_2, etc. since such names were used in RT's REST 1.0 API.

### CODE REVIEW

**Comment by gibus** [comment]
Hello, is there a reason to close this PR, or  bestpractical-mirror is just a bot which has gone wild?

**Comment by puck** [comment]
Hey @sunnavy any chance of merging this auto-closed PR? It provided a nicer work flow for creating tickets!

**Comment by unexceptable** [comment]
@bestpractical-mirror Why was this closed? This is amazingly useful! Otherwise you have to create a ticket, and THEN attachments... Which is needlessly complicated.

**Comment by unexceptable** [comment]
I assume that's actually a bot...

@sunnavy We were running this on our fork and it was amazingly useful, and we starting building it into our logic externally. Is there no chance at getting this merged? :(

**Comment by sunnavy** [comment]
I believe it's closed by accident. It's a useful feature to me too.

**Comment by unexceptable** [comment]
@sunnavy I guess also worth looking at: https://github.com/bestpractical/rt-extension-rest2/pull/17

and Making this patch follow the new pattern with `JSON` and `Attachments` vs `Json` and `attachment_<number>` from: https://github.com/bestpractical/rt-extension-rest2/pull/16

**Comment by unexceptable** [comment]
Cool, I've merged and released: https://gitlab.com/catalyst-cloud/rt-client/-/commit/a46ea45d00a196540b67dfbe514f66961ab07501

In my python rt-client, but I've left in this ability to add files on ticket create as I think it is definitely worth having, and I assume you're likely to merge it. :wink:

**Comment by puck** [comment]
I've created a pull request (as noted just above) in the main rt repo where the REST2 API now lives. I'll also updated this PR as at Catalyst we're still on RT 4.4.x and will continue to use this extension until we switch to RT 5.

**Comment by gibus** [comment]
Great, thanks very much @puck! I'm sorry I hadn't a chance to look at rest2 API for a while

**Comment by gibus** [comment]
Great, thanks very much @puck! I'm sorry I hadn't a chance to look at rest2 API for a while

**Pull request closed without merging**
