### PR TITLE
Add correspond attachments multipart

### PR DESCRIPTION
**Pull request by gibus**
This pull request is an addition to PR  #15 allowing to specify attachments for /ticket/:id/correspond|comment with a multipart/form-data POST request. Here's the doc:

Encoding the content of attachments file in MIME Base64 has the drawback
    of adding some processing overhead and to increase the sent data size by
    around 33%. RT's REST2 API provides another way to attach any binary or
    text file to your response or comment by POSTing, instead of a JSON
    request, a multipart/form-data request. This kind of request is similar
    to what the browser sends when you add attachments in RT's reply or
    comment form. As its name suggests, a multipart/form-data request
    message contains a series of parts, each representing a form field. To
    reply to or comment a ticket, the request has to include a field named
    Json, which, as previously, is a JSON object with Subject, Content,
    ContentType, TimeTaken properties. Files can then be attached by
    specifying a field named Attachment for each of them, with the content
    of the file as value and the appropriate MIME type.

    The curl invocation is quite straith forward:

        curl -X POST
             -H "Content-Type: multipart/form-data"
             -F 'Json={
                        "Subject"    : "Attachments in multipart/form-data",
                        "Content"    : "<p>I want <b>two</b> <em>attachments</em></p>"
                        "ContentType": "text/html",
                        "TimeTaken"  : "1"
                      };type=application/json'
             -F 'Attachment=@/tmp/my_image.png;type=image/png'
             -F 'Attachment=@~/.bashrc;type=text/plain'
             -H 'Authorization: token XX_TOKEN_XX'
                'XX_TICKET_URL_XX'/comment

    As a sidenote, fields for attached files can also be named attachment_1,
    attachment_2, etc. since such names were used in RT's REST 1.0 API.

### CODE REVIEW

**Comment by puck** [comment]
This is exactly what my Python dev colleagues have been asking for! Fantastic, I'll ask them to try it out this week.

**Comment by gibus** [comment]
Great it is useful! It was asked by some of our customers and also on RT Community Forum some days ago.

**Comment by puck** [comment]
Oops, wrong branch. Ignore this message.

**Comment by puck** [comment]
Right, my branch with master merged is here:
https://github.com/catalyst-cloud/rt-extension-rest2/tree/add-correspond-attachments-multipart

**Comment by sunnavy** [comment]
I switched to a single parameter "Attachments" instead of a list of "Attachment", "Attachment_1", etc, for simplicity and it's also easier to retain the attachment order.

I also updated the case of "Json" to "JSON", which is more commonly used.

Merged and thanks!

**Pull request closed without merging**
